# nixpacks.toml - Railway build configuration
[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"

---

# backend/railway.json - Service configuration
{
  "name": "email-assistant-backend",
  "build": {
    "commands": [
      "pip install -r requirements.txt"
    ]
  },
  "start": {
    "command": "uvicorn app:app --host 0.0.0.0 --port $PORT"
  },
  "env": {
    "PYTHON_VERSION": "3.9"
  }
}

---

# backend/Procfile - Alternative process file
web: uvicorn app:app --host 0.0.0.0 --port $PORT

---

# .github/workflows/deploy.yml - Optional GitHub Actions
name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      run: railway up --service backend
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}